[modName]
	# Назва: Формат назви мода
	# Опис: Форматує назв модів у підказках для інтерфейсу JEI. Залиште порожнім, щоби вимкнути.
	# Дійсні значення: A chat formatting string.
	# Use these formatting colors:
	# black dark_blue dark_green dark_aqua dark_red dark_purple gold gray dark_gray blue green aqua red light_purple yellow white
	# With these formatting options:
	# obfuscated bold strikethrough underline italic
	# Усталене значення: blue italic
	modNameFormat = blue italic


