[appearance]
	# Назва: Панель пошуку по центру
	# Опис: Переміщає рядок пошуку JEI унизу по центру екрана.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	centerSearch = false

	# Назва: Висота інтерфейсу рецепта
	# Опис: Максимальна висота інтерфейсу рецептів (у пікселях).
	# Дійсні значення: Any integer greater than or equal to 175
	# Усталене значення: 350
	recipeGuiHeight = 350


[cheating]
	# Назва: Режим надання
	# Опис: Виберіть, чи повинен JEI давати інгредієнти безпосередньо в інвентар, чи підбирати їх за допомогою миші.
	# Дійсні значення: [INVENTORY, MOUSE_PICKUP]
	# Усталене значення: MOUSE_PICKUP
	giveMode = MOUSE_PICKUP

	# Назва: Брати предмети на гарячу панель гарячими клавішами
	# Опис: Умикає брання предметів на панель швидкого доступу за допомогою Shift + цифрові клавіші.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	cheatToHotbarUsingHotkeysEnabled = false

	# Назва: Показати приховані інгредієнти
	# Опис: Умикає показ інгредієнтів, яких немає в творчому меню.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	showHiddenIngredients = false

	# Назва: Показати рецепти теґів
	# Опис: Показує рецепти для теґів інгредієнтів, таких як теґи предметів і теґи блоків.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	showTagRecipesEnabled = false


[bookmarks]
	# Назва: Додати закладки на передній план
	# Опис: Якщо ввімкнено, нові закладки додаються на початку списку. Якщо вимкнено, у кінець.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	addBookmarksToFrontEnabled = false

	# Назва: Перетягніть, щоби змінити порядок закладок
	# Опис: Умикає перетягування закладок, щоби змінити їх порядок у списку.
	# Дійсні значення: [true, false]
	# Усталене значення: true
	dragToRearrangeBookmarksEnabled = true


[tooltips]
	# Назва: Функції підказок закладок
	# Опис: Додаткові функції для підказок закладок.
	# Дійсні значення: A comma-separated list containing values of:
	# [PREVIEW, INGREDIENTS]
	# Усталене значення: PREVIEW
	bookmarkTooltipFeatures = PREVIEW

	# Назва: Shift для підказок закладок
	# Опис: Утримуйте Shift, щоби показати функції підказок закладок.
	# Дійсні значення: [true, false]
	# Усталене значення: true
	holdShiftToShowBookmarkTooltipFeatures = true

	# Назва: Показати назви вкладок творчости
	# Опис: Показує назви вкладок творчости у підказках інгредієнтів.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	showCreativeTabNamesEnabled = false

	# Назва: Показати вміст теґу
	# Опис: Показує вміст теґів у підказках під час перегляду інгредієнтів рецепта.
	# Дійсні значення: [true, false]
	# Усталене значення: true
	tagContentTooltipEnabled = true

	# Назва: Приховати вміст теґу одного інгредієнта
	# Опис: Приховує вміст теґу у підказках, якщо в теґу є лише один інгредієнт.
	# Дійсні значення: [true, false]
	# Усталене значення: true
	hideSingleTagContentTooltipEnabled = true

	# Назва: Короткий опис інгредієнтів рецепта
	# Опис: Показує короткий опис інгредієнтів, необхідних для рецепта, у підказці вихідного інгредієнта.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	enableRecipesGuiIngredientsSummary = false


[performance]
	# Назва: Пошук мало пам'яті
	# Опис: Установлює пошук у режим малого обсягу пам'яті (робить пошук повільним, але використовує менше оперативної пам'яті).
	# Дійсні значення: [true, false]
	# Усталене значення: false
	lowMemorySlowSearchEnabled = false


[lookups]
	# Назва: Уміст рідини пошуку
	# Опис: Під час пошуку рецептів із продуктами, які містять рідини, також шукайте рецепти для рідин.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	lookupFluidContentsEnabled = false

	# Назва: Пошук теґів ItemBlock
	# Опис: Під час пошуку теґів предметів також додайте теґи для стандартних блоків, які містяться в предметах.
	# Дійсні значення: [true, false]
	# Усталене значення: true
	lookupBlockTagsEnabled = true


[lookupHistory]
	# Назва: Увімкнено
	# Опис: Показує або приховує накладення історії пошуку.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	enabled = false

	# Назва: Максимум рядків
	# Опис: Максимальна кількість рядків для показу в накладенні історії пошуку.
	# Дійсні значення: An integer in the range [1, 7] (inclusive)
	# Усталене значення: 2
	maxRows = 2

	# Назва: Макс. інгредієнтів
	# Опис: Максимальна кількість інгредієнтів історії пошуку для збереження.
	# Дійсні значення: An integer in the range [10, 1000] (inclusive)
	# Усталене значення: 100
	maxIngredients = 100

	# Назва: Сторона показу
	# Опис: Бокова частина екрана для показу накладання історії пошуку.
	# Дійсні значення: [LEFT, RIGHT]
	# Усталене значення: LEFT
	displaySide = LEFT


[advanced]
	# Назва: Ловити помилки відтворення
	# Опис: Ловити помилки промальовування модових інгредієнтів і намагатися відновити їх замість збою.
	# Дійсні значення: [true, false]
	# Усталене значення: true
	catchRenderErrorsEnabled = true


[input]
	# Назва: Затримка перетягування
	# Опис: Кількість мілісекунд перед довгим натисканням миші вважається перетягуванням миші.
	# Дійсні значення: An integer in the range [0, 1000] (inclusive)
	# Усталене значення: 150
	dragDelayInMilliseconds = 150

	# Назва: Швидкість плавного прокручування
	# Опис: Швидкість прокручування коліщатка миші в полях прокручування з плавним прокручуванням. Вимірюється в пікселях.
	# Дійсні значення: An integer in the range [1, 50] (inclusive)
	# Усталене значення: 9
	smoothScrollRate = 9


[sorting]
	# Назва: Етапи сортування інгредієнтів
	# Опис: Порядок сортування для списку інгредієнтів.
	# Дійсні значення: A comma-separated list containing values of:
	# [MOD_NAME, INGREDIENT_TYPE, ALPHABETICAL, CREATIVE_MENU, TAG, ARMOR, MAX_DURABILITY]
	# Усталене значення: MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU
	ingredientSortStages = MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU

	# Назва: Етапи сортування рецептів
	# Опис: Порядок сортування для показаних рецептів.
	# Дійсні значення: A comma-separated list containing values of:
	# [BOOKMARKED, CRAFTABLE]
	# Усталене значення: BOOKMARKED, CRAFTABLE
	recipeSorterStages = BOOKMARKED, CRAFTABLE


[search]
	# Назва: Режим пошуку імені @Мод
	# Опис: Режим пошуку назв модів (префікс: @).
	# Дійсні значення: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Усталене значення: REQUIRE_PREFIX
	modNameSearchMode = REQUIRE_PREFIX

	# Назва: #Режим пошуку тегів
	# Опис: Режим пошуку теґів (префікс: #).
	# Дійсні значення: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Усталене значення: REQUIRE_PREFIX
	tagSearchMode = REQUIRE_PREFIX

	# Назва: Режим пошуку $Опис
	# Опис: Режим пошуку підказок (префікс: $).
	# Дійсні значення: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Усталене значення: ENABLED
	tooltipSearchMode = ENABLED

	# Назва: ^Режим пошуку кольорів
	# Опис: Режим пошуку кольорів (префікс: ^).
	# Дійсні значення: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Усталене значення: DISABLED
	colorSearchMode = DISABLED

	# Назва: &Режим пошуку ідентифікатора
	# Опис: Режим пошуку ідентифікатора (префікс: &).
	# Дійсні значення: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Усталене значення: DISABLED
	resourceLocationSearchMode = DISABLED

	# Назва: Режим пошуку %вкладка творчости
	# Опис: Режим пошуку назв вкладок творчого режиму (префікс: %).
	# Дійсні значення: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Усталене значення: DISABLED
	creativeTabSearchMode = DISABLED

	# Назва: Розширені підказки пошуку
	# Опис: Пошук у розширених підказках (видимі за допомогою F3 + H).
	# Дійсні значення: [true, false]
	# Усталене значення: false
	searchAdvancedTooltips = false

	# Назва: Пошук ID модів
	# Опис: Шукати ідентифікатори модів на додаток до назв модів.
	# Дійсні значення: [true, false]
	# Усталене значення: true
	searchModIds = true

	# Назва: Пошук модоних псевдонімів
	# Опис: Шукати псевдоніми модів (альтернативні імена), додані плаґінами, на додаток до назв модів.
	# Дійсні значення: [true, false]
	# Усталене значення: true
	searchModAliases = true

	# Назва: Пошук короткої назви модів
	# Опис: Пошук за скороченими першими літерами назви мода.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	searchShortModNames = false

	# Назва: Псевдоніми інгредієнтів пошуку
	# Опис: Шукати назви інгредієнтів (альтернативні назви), додані плагінами, на додаток до назв інгредієнтів.
	# Дійсні значення: [true, false]
	# Усталене значення: true
	searchIngredientAliases = true


[ingredientList]
	# Назва: Максимум рядків
	# Опис: Максимальна кількість показаних рядків.
	# Дійсні значення: An integer in the range [1, 100] (inclusive)
	# Усталене значення: 16
	maxRows = 16

	# Назва: Максимум стовпців
	# Опис: Максимальна кількість показаних стовпців.
	# Дійсні значення: An integer in the range [2, 100] (inclusive)
	# Усталене значення: 9
	maxColumns = 9

	# Назва: Горизонтальне вирівнювання
	# Опис: Горизонтальне вирівнювання списку інгредієнтів у доступній області.
	# Дійсні значення: [LEFT, CENTER, RIGHT]
	# Усталене значення: RIGHT
	horizontalAlignment = RIGHT

	# Назва: Вертикальне вирівнювання
	# Опис: Вертикальне вирівнювання списку інгредієнтів у доступній області.
	# Дійсні значення: [TOP, CENTER, BOTTOM]
	# Усталене значення: TOP
	verticalAlignment = TOP

	# Назва: Видимість навігації
	# Опис: Показує кнопки верхньої сторінки. Використовуйте AUTO_HIDE, щоби показувати її, лише коли є кілька сторінок.
	# Дійсні значення: [ENABLED, AUTO_HIDE, DISABLED]
	# Усталене значення: ENABLED
	buttonNavigationVisibility = ENABLED

	# Назва: Малювати тло інтерфейсу
	# Опис: Умикає малювання текстури тла за списком інгредієнтів.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	drawBackground = false


[bookmarkList]
	# Назва: Максимум рядків
	# Опис: Максимальна кількість показаних рядків.
	# Дійсні значення: An integer in the range [1, 100] (inclusive)
	# Усталене значення: 16
	maxRows = 16

	# Назва: Максимум стовпців
	# Опис: Максимальна кількість показаних стовпців.
	# Дійсні значення: An integer in the range [2, 100] (inclusive)
	# Усталене значення: 9
	maxColumns = 9

	# Назва: Горизонтальне вирівнювання
	# Опис: Горизонтальне вирівнювання списку закладок у доступній області.
	# Дійсні значення: [LEFT, CENTER, RIGHT]
	# Усталене значення: LEFT
	horizontalAlignment = LEFT

	# Назва: Вертикальне вирівнювання
	# Опис: Вертикальне вирівнювання списку закладок у доступній області.
	# Дійсні значення: [TOP, CENTER, BOTTOM]
	# Усталене значення: TOP
	verticalAlignment = TOP

	# Назва: Видимість навігації
	# Опис: Видимість кнопок верхньої сторінки. Використовуйте AUTO_HIDE, щоби показувати її, лише якщо є кілька сторінок.
	# Дійсні значення: [ENABLED, AUTO_HIDE, DISABLED]
	# Усталене значення: ENABLED
	buttonNavigationVisibility = ENABLED

	# Назва: Малювати тло інтерфейсу
	# Опис: Умикає малювання текстури тла за списком закладок.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	drawBackground = false


