[debug]
	# Назва: Режим налагодження
	# Опис: Увімкнути режим налагодження
	# Дійсні значення: [true, false]
	# Усталене значення: false
	debugMode = false

	# Назва: Налагодження інтерфейсу
	# Опис: Умикає режим налагодження інтерфейсу
	# Дійсні значення: [true, false]
	# Усталене значення: false
	debugGuis = false

	# Назва: Уведення налагодження
	# Опис: Умикає режим уведення налагодження
	# Дійсні значення: [true, false]
	# Усталене значення: false
	debugInputs = false

	# Назва: Спливні підказки інформації про налагодження
	# Опис: Додає інформацію про налагодження до підказок інгредієнтів, якщо ввімкнено розширені підказки.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	debugInfoTooltipsEnabled = false

	# Назва: Увімкнути предмети тесту на збій
	# Опис: Додає інгредієнти до JEI, які навмисно аварійно завершують роботу, щоби допомогти налагодити JEI.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	crashingTestItemsEnabled = false

	# Назва: jei.config.debug.debug.crashingTestRecipesEnabled
	# Опис: jei.config.debug.debug.crashingTestRecipesEnabled.description
	# Дійсні значення: [true, false]
	# Усталене значення: false
	crashingTestRecipesEnabled = false

	# Назва: Статистика дерева пошуку журналу
	# Опис: Реєструє інформацію про дерева суфіксів, які використовуються для пошуку, щоби допомогти налагодити JEI.
	# Дійсні значення: [true, false]
	# Усталене значення: false
	logSuffixTreeStats = false


