#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.cake.creategarnished]
			pound_cake = true

		[types.cake.createfood]
			apple_cream_cake = true
			berry_cream_cake = true
			berry_cream_cake_chorus_fruit = true
			berry_cream_cake_glow_berry = true
			berry_cream_cake_sweet_berry = true
			chocolate_cream_cake = true
			chocolate_cream_cake_butterscotch = true
			chocolate_cream_cake_caramel = true
			chocolate_cream_cake_chocolate = true
			chocolate_cream_cake_dark_chocolate = true
			chocolate_cream_cake_toffee = true
			chocolate_cream_cake_white_chocolate = true
			chocolate_cream_chocolate_cake = true
			chorus_fruit_cream_cake = true
			chorus_fruit_cream_cake_chorus_fruit = true
			chorus_fruit_cream_cake_glow_berry = true
			chorus_fruit_cream_cake_sweet_berry = true
			cream_cake = true
			cream_cake_chorus_fruit = true
			cream_cake_glow_berry = true
			cream_chocolate_cake = true
			glow_berry_cream_cake = true
			glow_berry_cream_cake_chorus_fruit = true
			glow_berry_cream_cake_glow_berry = true
			glow_berry_cream_cake_sweet_berry = true
			melon_cream_cake = true
			ube_cream_ube_cake = true

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

		[types.cake.natures_spirit]
			cheese_block = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.createdieselgenerators]
			chip_wood = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.betterend]
			dragon_tree = true
			end_lotus = true
			helix_tree = true
			jellyshroom = true
			lacugrove = true
			lucernia = true
			mossy_glowshroom = true
			pythadendron = true
			tenanea = true
			umbrella_tree = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.regions_unexplored]
			alpha = true
			baobab = true
			blackwood = true
			brimwood = true
			cobalt = true
			cypress = true
			dead = true
			eucalyptus = true
			joshua = true
			kapok = true
			larch = true
			magnolia = true
			maple = true
			palm = true
			pine = true
			redwood = true
			socotra = true
			willow = true
			wisteria = true
			pink_bioshroom = true
			yellow_bioshroom = true
			blue_bioshroom = true
			green_bioshroom = true

		[types.wood_type.natures_spirit]
			redwood = true
			sugi = true
			wisteria = true
			fir = true
			willow = true
			aspen = true
			maple = true
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			mahogany = true
			saxaul = true

		[types.leaves_type.creategarnished]
			pine_nut = true
			hazelnut = true
			almond = true
			blossoming_almond = true
			chestnut = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.iceandfire]
			dreadwood = true

		[types.leaves_type.betterend]
			dragon_tree = true
			lacugrove = true
			lucernia = true
			pythadendron = true
			tenanea = true

		[types.leaves_type.twilightforest]
			thorn = true
			beanstalk = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.regions_unexplored]
			alpha = true
			apple_oak = true
			ashen = true
			bamboo = true
			baobab = true
			blackwood = true
			blue_magnolia = true
			brimwood = true
			cypress = true
			dead_pine = true
			dead = true
			eucalyptus = true
			flowering = true
			golden_larch = true
			kapok = true
			larch = true
			magnolia = true
			maple = true
			orange_maple = true
			palm = true
			pine = true
			pink_magnolia = true
			red_maple = true
			redwood = true
			silver_birch = true
			small_oak = true
			socotra = true
			white_magnolia = true
			willow = true
			sky_wisteria = true
			lavender_wisteria = true
			salmon_wisteria = true

		[types.leaves_type.natures_spirit]
			frosty_redwood = true
			redwood = true
			sugi = true
			wisteria = true
			white_wisteria = true
			part_white_wisteria = true
			blue_wisteria = true
			part_blue_wisteria = true
			pink_wisteria = true
			part_pink_wisteria = true
			purple_wisteria = true
			part_purple_wisteria = true
			frosty_fir = true
			fir = true
			willow = true
			aspen = true
			yellow_aspen = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			mahogany = true
			saxaul = true

		[types.lantern.natures_spirit]
			paper_lantern = true
			white_paper_lantern = true
			light_gray_paper_lantern = true
			gray_paper_lantern = true
			black_paper_lantern = true
			brown_paper_lantern = true
			red_paper_lantern = true
			orange_paper_lantern = true
			yellow_paper_lantern = true
			lime_paper_lantern = true
			green_paper_lantern = true
			blue_paper_lantern = true
			light_blue_paper_lantern = true
			cyan_paper_lantern = true
			purple_paper_lantern = true
			magenta_paper_lantern = true
			pink_paper_lantern = true

#Disables specific entries
[entries]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			shelf = true
			cupboard = true
			dining_bench = true
			bench = true
			drawer = true
			pillar_trim = true
			side_table = true
			nightstand = true
			couch = true
			table = true
			chair = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.another_furniture]
			shelf = true
			bench = true
			flower_box = true
			shutter = true
			table = true
			drawer = true
			chair = true

		[entries.wood_type.tradeworks]
			shelf = true
			side_shelf = true
			metal_shelf = true

		[entries.wood_type.unusual_furniture]
			celling_lamp = true
			table = true
			chair = true
			railing = true
			carved = true
			stool = true
			bench = true
			drawer = true
			coffee_table = true
			beam = true
			shelf = true
			open_riser_stairs = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.quark]
			vertical_planks = true
			chest = true
			ladder = true
			hollow_log = true
			post = true
			trapped_chest = true
			bookshelf = true
			stripped_post = true
			vertical_slab = true

		[entries.wood_type.backpacked]
			backpack_shelf = true

		[entries.wood_type.regions_unexplored]
			branch = true

		[entries.wood_type.twilightforest]
			drying_rack = true
			banister = true
			hollow_log_climbable = true
			hollow_log_horizontal = true
			hollow_log_vertical = true
			hollow_log = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.leaves_type.regions_unexplored]
			shrub = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true
